server:
  port: 8095
  servlet:
    context-path: /api/admin

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/teambuilder_db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        default_schema: admin
  output:
    ansi:
      enabled : always

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/auth/realm/tba-realm
#        registration:
#          keycloak:
#            client-id: tba-client

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

belbin:
  host: http://localhost:8090
  context-path: /api/belbin