version: '3.8'
name: tba-dev

services:
  tba-database:
    image: 'postgres'
    container_name: tba-db-dev
    environment:
      - POSTGRES_DB=teambuilder_db
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - tbaNetwork



networks:
  tbaNetwork:
    name: tbaNetwork
    driver: bridge