server:
  port: 8093
  servlet:
    context-path: /api/teambuilder

spring:
  datasource:
    url : jdbc:postgresql://localhost:6543/teambuilder_db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        default_schema: teambuilder
  output:
    ansi:
      enabled : always
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


belbin:
  host: localhost:8090
  context-path: /api/belbin
hardskills:
  host: localhost:8091
  context-path: /api/hardskills